#spring:
#  datasource:
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: 
#      driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
      primary:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
      secondary:
        url: jdbc:mysql://localhost:3306/yun
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver