spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver 
    max-active: 20
    max-idle: 5
    min-idle: 1
    initial-size: 2

server:
  port: 8800